version: '3.1'

services:
  ember:
    build: ember-dev/
    image: oapass/ember-dev
    container_name: ember
    env_file: .env
    volumes:
      - ../../:/app:Z
      - /app/node_modules
    ports:
      - '${EMBER_PORT}:${EMBER_PORT}'
    networks:
      - back

  fcrepo:
    image: oapass/fcrepo:4.7.5-3.3@sha256:0d0e007409fd03f9bd4e65657d3198381c4cce3d7c62a1c0be1a53cb8123461d
    container_name: fcrepo
    env_file: .env
    ports:
      - '${FCREPO_PORT}:${FCREPO_PORT}'
      - '${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}'
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on:
      - assets
      - activemq

  schemaservice:
    image: oapass/schema-service:v0.1.1
    container_name: schemaservice
    env_file: .env
    ports:
      - "${SCHEMA_SERVICE_PORT}:${SCHEMA_SERVICE_PORT}"
    networks:
      - front
      - back

  activemq:
    image: oapass/activemq:20180618@sha256:e3cd47a1bc4c21899fc34e5ac7198f6c069f4148296bad0ce619cc2bdda5f435
    container_name: activemq
    env_file: .env
    ports:
      - '${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}'
      - '${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}'
      - '${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}'
    networks:
      - front
      - back

  static-html:
    image: oapass/static-html:20181101-c7be0f8@sha256:38e3098807e250141d5efd4a3db511e248932353d29d887b4c6dd789725447c4
    container_name: static-html
    env_file: .env
    ports:
      - '${STATIC_HTML_PORT}:${STATIC_HTML_PORT}'
    networks:
      - back
      - front

  proxy:
    image: oapass/httpd-proxy:20190306@sha256:63770ee48bfaf251565b2e3ffd593284ed3783ef1b1c44390a60d57c9764009c
    container_name: proxy
    networks:
      - front
      - back
    ports:
      - '80:80'
      - '443:443'

  idp:
    image: oapass/idp:20181012@sha256:59d920bd4c6a51d12c0961717f38d743710f1bd8221c2b6c8dda6746ac224d7b
    container_name: idp
    depends_on:
      - ldap
    environment:
      - JETTY_MAX_HEAP=64m
      - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
      - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
      - '4443'
    networks:
      - back
    secrets:
      - source: idp_backchannel
      - source: idp_browser
      - source: idp_encryption
      - source: idp_signing
      - source: idp_sealer

  ldap:
    image: oapass/ldap:20181106@sha256:065b91e74de5565df7d4459590c51986368ee157f73d81eb10232c7dadcb98e4
    container_name: ldap
    networks:
      - back

  sp:
    image: oapass/sp:20190306@sha256:6df4a3307fcee68c3f9b1e7fecaa58c0357da1713450a63173ab8a2c79cf14d5
    container_name: sp
    networks:
      - back
    secrets:
      - source: sp_key

  indexer:
    image: oapass/indexer:0.0.17-3.2-SNAPSHOT@sha256:b572bb48814fb1624a29556fd648de7b4f432c9f65f904d609efcf7f8ac36948
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data
    ports:
      - '${ES_PORT}:${ES_PORT}'
    networks:
      - front
      - back
    depends_on:
      - assets

  assets:
    image: birkland/assets:2019-03-06_3.3@sha256:e4c59e625eaf28cb4524dbe54a4e5dbf11adf71347470afb8810a75274f596c7
    volumes:
      - passdata:/data

volumes:
  passdata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
