version: '3.1'

services:
  ember:
    build: ember-dev/
    image: oapass/ember-dev
    container_name: ember
    env_file: .env
    volumes:
      - ../:/app:Z
      - /app/node_modules
    ports:
      - '${EMBER_PORT}:${EMBER_PORT}'
    networks:
      - back

  fcrepo:
    image: oapass/fcrepo:4.7.5-3.5@sha256:bb44fff182ace1d0d57372f297cbab8cc04c662db2d10a061213178b7c0c9bba
    container_name: fcrepo
    env_file: .env
    ports:
      - '${FCREPO_PORT}:${FCREPO_PORT}'
      - '${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}'
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on:
      - assets
      - activemq

  schemaservice:
    image: oapass/schema-service:v0.5.2@sha256:572dcfe965c5588564de22accd1ecaca3d3b141ba1097c9830026420ca3557c4
    container_name: schemaservice
    env_file: .env
    ports:
      - "${SCHEMA_SERVICE_PORT}:${SCHEMA_SERVICE_PORT}"
    networks:
      - front
      - back

  activemq:
    image: oapass/activemq:20180618@sha256:e3cd47a1bc4c21899fc34e5ac7198f6c069f4148296bad0ce619cc2bdda5f435
    container_name: activemq
    env_file: .env
    ports:
      - '${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}'
      - '${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}'
      - '${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}'
    networks:
      - front
      - back

  static-html:
    image: oapass/static-html:jhu-20200422-aaa9d81@sha256:991aa8bce01254513ab7437e33c05545f157acd256802079cbe70bd7a9eeb7e9
    container_name: static-html
    env_file: .env
    ports:
      - '${STATIC_HTML_PORT}:${STATIC_HTML_PORT}'
    networks:
      - back
      - front

  proxy:
    image: oapass/httpd-proxy:201900508@sha256:a915ada2286a551d32b0494d4ce874ba7fe204c07f029cc9bba5e05b2a9087fc
    container_name: proxy
    networks:
      - front
      - back
    ports:
      - '80:80'
      - '443:443'

  idp:
    image: oapass/idp:20181012@sha256:59d920bd4c6a51d12c0961717f38d743710f1bd8221c2b6c8dda6746ac224d7b
    container_name: idp
    depends_on:
      - ldap
    environment:
      - JETTY_MAX_HEAP=64m
      - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
      - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
      - '4443'
    networks:
      - back
    secrets:
      - source: idp_backchannel
      - source: idp_browser
      - source: idp_encryption
      - source: idp_signing
      - source: idp_sealer

  ldap:
    image: oapass/ldap:20181106@sha256:065b91e74de5565df7d4459590c51986368ee157f73d81eb10232c7dadcb98e4
    container_name: ldap
    networks:
      - back

  sp:
    image: oapass/sp:201900508@sha256:94eb4796da7bed604468e295422be23c94f0119591fb37e11b40ce0376bca49f
    container_name: sp
    networks:
      - back
    secrets:
      - source: sp_key

  indexer:
    image: oapass/indexer:0.0.18-3.4-1@sha256:3375ea702e0a1c7a5e0e7e06635d28e49af436aeb1c3d88a03d4cb494d7b40bf
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data
    ports:
      - '${ES_PORT}:${ES_PORT}'
    networks:
      - front
      - back
    depends_on:
      - assets

  assets:
    image: birkland/assets:2019-04-08_3.4@sha256:7ec44bd52d7cf635ad05a3f509cf7439e187b7768b8a05abae81b49744ec9d5f
    volumes:
      - passdata:/data

  policyservice:
    image: oapass/policy-service:v0.1.1@sha256:7eec368c7da024c1a3a955e80c2185928f86188e2e870ed9bf11846dc0153980
    container_name: policyservice
    env_file: .env
    ports:
      - "${POLICY_SERVICE_PORT}:${POLICY_SERVICE_PORT}"
    networks:
      - front
      - back

  doiservice:
    image: oapass/doi-service:version1.0.0@sha256:3f244a7e0d2bc8f47fa4cca792984cf2f2672eb28a9a650db72ae7beee7e9b4b
    container_name: doiservice
    env_file: .env
    ports:
      - "${PASS_DOI_SERVICE_PORT}:8080"
    networks:
      - front
      - back

volumes:
  passdata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
